04
ruvater/made_2019_algo pull request #1
Opened 2019-11-08 07:19 UTC by ruvater

2019-11-08 23:28 UTC, ylyubimov requested changes
Приложи комментарием ссылку на контест.
И напиши свое ФИО, чтобы я мог ник сопоставить
Как все сделаешь перепризови меня, выбрав ревьювером еще раз.

2019-11-08 23:28 UTC, ylyubimov commented on 04/main.cpp
> +        std::cin >> a[i];
По условию задачи, массив не влезает в память => нельзя считывать весь массив. Читай по K элементов

2019-11-08 23:28 UTC, ylyubimov commented on 04/main.cpp
> +int KthSmallest(int *a, int n, int k) {
Давай добавим класс-сравнения и сделаем фунцкию шаблонной

2019-11-09 08:48 UTC, ruvater commented on 04/main.cpp
> +        std::cin >> a[i];
Это же не 3-я задача, тут прямо в условии написано:

Требования к дополнительной памяти: O(n).

2019-11-09 09:17 UTC, ruvater commented
https://contest.yandex.ru/contest/14768/run-report/23848265/

2019-11-09 09:17 UTC, ruvater commented
Назаров Владимир

2019-11-09 09:18 UTC, ruvater commented
Владимир Назаров

2019-11-09 09:18 UTC, ruvater commented on 04/main.cpp
> +int KthSmallest(int *a, int n, int k) {
Добавил

2019-11-12 07:17 UTC, ylyubimov approved these changes
Все ок

2019-11-12 07:17 UTC, ylyubimov commented on 04/main.cpp
> +        std::cin >> a[i];
Да, сорри что-то попутал

2019-11-15 18:46 UTC, merged